version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
  ports:
    - "9091:9090"  # Expose Prometheus outside on port 9091
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring

networks:
  monitoring:
